class Square {
    constructor(sID, type) {
        this.id = sID
        this.type = type
    }
}

class Generator extends Square {
    constructor(sID, type, element) {
        super(sID, type)
        this.element = element
        this.description = 'Generates $2';
        this.cost = 5;
        this.charges = 5;
        this.maxCharges = 5;
        this.layerCostMod = 1.75;
        this.amount = 2;
        this.upgrades = {
            generated: {
                name: 'Amount Generated',
                id: 'generated',
                description: 'Doubles the amount generated by this generator.',
                layerCostMod: 1.6,
                levelCostMod: 1.4,
                cost: 15,
                level: 1
            }
        }
    }

    currentUpgradeCost(upgrade) {
        let currentCost = this.upgrades[upgrade].cost
        let currentLevel = this.upgrades[upgrade].level
        let modifier = this.upgrades[upgrade].levelCostMod

        return currentCost * (1.4 ** (currentLevel - 1))
    }

    buyUpgrade(upgrade) {
        if (player.money >= this.currentUpgradeCost(upgrade)) {
            player.money -= this.upgrades[upgrade].cost
            this.upgrades[upgrade].level++
            this.element.innerHTML = this.upgrades[upgrade].level          
        }
    }
}

const buildings = {
    Generator: {
        name: 'Generator',
        description: 'Generates $2.',
        cost: 5,
        charges: 5,
        maxCharges: 5,
        layerCostMod: 1.75,
        amount: 2,
        upgrades: {
            generated: {
                name: 'Amount Generated',
                id: 'generated',
                description: 'Doubles the amount generated by this generator.',
                layerCostMod: 1.6,
                levelCostMod: 1.4,
                cost: 15,
                level: 1
            },
            charges: {
                name: 'Max Charges',
                id: 'charges',
                description: 'Adds 4 more max charges to this generator.',
                cost: 25,
                layerCostMod: 1.9,
                levelCostMod: 1.8,
                level: 1
            }
        }
    },
    // More buildings to come...
}




const boardUpgrades = {
    gameSpeed: {
        id: 'gameSpeed',
        name: 'Layer Speed',
        description: 'Squares move along this layer quicker.',
        cost: 100,
        layerCostMod: 3,
        levelCostMod: 4,
        levelMulti: 1.2
    },
    boardSize: {
        id: 'boardSize',
        name: 'Add Layer',
        description: 'Add another layer to the grid.',
        cost: 1000,
        layerCostMod: 3,
        levelCostMod: 1
    }
}

