const buildings = {
    Generator: {
        name: 'Generator',
        description: 'Generates $2.',
        cost: 5,
        charges: 5,
        maxCharges: 5,
        layerCostMod: 1.75,
        amount: 2,
        upgrades: {
            generated: {
                name: 'Amount Generated',
                id: 'generated',
                description: 'Doubles the amount generated by this generator.',
                layerCostMod: 1.6,
                levelCostMod: 1.4,
                cost: 15,
                level: 1
            },
            charges: {
                name: 'Max Charges',
                id: 'charges',
                description: 'Adds 4 more max charges to this generator.',
                cost: 25,
                layerCostMod: 1.9,
                levelCostMod: 1.8,
                level: 1
            }
        }
    },
    // Multi: {
    //     name: 'Multi (todo)',
    //     description: 'Multiplies the next square.',
    //     cost: 10,
    //     charges: 5,
    //     maxCharges: 5,
    //     amount: 2,
    //     upgrades: {
    //         place: {
    //             name: 'place',
    //             description: 'placeholder (not implemented.)',
    //             cost: 25
    //         },
    //         place2: {
    //             name: 'place2',
    //             description: 'placeholdre2 (not implemented.)',
    //             cost: 100
    //         }
    //     }
    // },
    // Reverse: {
    //     name: 'Reverse (todo)',
    //     description: 'Reverses direction when hitting this square. (not implemented.)',
    //     cost: 25
    // }
}




const boardUpgrades = {
    gameSpeed: {
        id: 'gameSpeed',
        name: 'Layer Speed',
        description: 'Squares move along this layer quicker.',
        cost: 100,
        layerCostMod: 3,
        levelCostMod: 4,
        levelMulti: 1.2
    },
    boardSize: {
        id: 'boardSize',
        name: 'Add Layer',
        description: 'Add another layer to the grid.',
        cost: 1000,
        layerCostMod: 3,
        levelCostMod: 1
    }
}

